excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://themiyaplotly.github.io
title: Awesome
email: themiyananayakkara@yahoo.co.uk
author: themiyaplotly
description: My awesome new site
paginate: 3
google_analytics: 